package com.inkubator.hrm.entity;
// Generated Mar 6, 2014 12:14:43 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Biodata generated by hbm2java
 */
@Entity
@Table(name="biodata"
    ,catalog="hrm"
)
public class Biodata  implements java.io.Serializable {


     private long id;
     private String nama;
     private Set<HrmUser> hrmUsers = new HashSet<HrmUser>(0);

    public Biodata() {
    }

	
    public Biodata(long id, String nama) {
        this.id = id;
        this.nama = nama;
    }
    public Biodata(long id, String nama, Set<HrmUser> hrmUsers) {
       this.id = id;
       this.nama = nama;
       this.hrmUsers = hrmUsers;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    
    @Column(name="nama", nullable=false, length=100)
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="biodata")
    public Set<HrmUser> getHrmUsers() {
        return this.hrmUsers;
    }
    
    public void setHrmUsers(Set<HrmUser> hrmUsers) {
        this.hrmUsers = hrmUsers;
    }




}


