package com.inkubator.hrm.entity;
// Generated Feb 27, 2014 10:10:16 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * HrmUser generated by hbm2java
 */
@Entity
@Table(name="hrm_user"
    ,catalog="hrm"
    , uniqueConstraints = @UniqueConstraint(columnNames="user_id") 
)
public class HrmUser  implements java.io.Serializable {


     private long id;
     private Integer version;
     private Biodata biodata;
     private String userId;
     private String password;
     private Integer isActive;
     private Integer isLock;
     private Integer isExpired;
     private String createdBy;
     private String updatedBy;
     private Date createdOn;
     private Date updatedOn;
     private Set<HrmUserRole> hrmUserRoles = new HashSet<HrmUserRole>(0);

    public HrmUser() {
    }

	
    public HrmUser(long id) {
        this.id = id;
    }
    public HrmUser(long id, Biodata biodata, String userId, String password, Integer isActive, Integer isLock, Integer isExpired, String createdBy, String updatedBy, Date createdOn, Date updatedOn, Set<HrmUserRole> hrmUserRoles) {
       this.id = id;
       this.biodata = biodata;
       this.userId = userId;
       this.password = password;
       this.isActive = isActive;
       this.isLock = isLock;
       this.isExpired = isExpired;
       this.createdBy = createdBy;
       this.updatedBy = updatedBy;
       this.createdOn = createdOn;
       this.updatedOn = updatedOn;
       this.hrmUserRoles = hrmUserRoles;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bio_data_id")
    public Biodata getBiodata() {
        return this.biodata;
    }
    
    public void setBiodata(Biodata biodata) {
        this.biodata = biodata;
    }

    
    @Column(name="user_id", unique=true, length=45)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }

    
    @Column(name="password", length=65535)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="is_active")
    public Integer getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Integer isActive) {
        this.isActive = isActive;
    }

    
    @Column(name="is_lock")
    public Integer getIsLock() {
        return this.isLock;
    }
    
    public void setIsLock(Integer isLock) {
        this.isLock = isLock;
    }

    
    @Column(name="is_expired")
    public Integer getIsExpired() {
        return this.isExpired;
    }
    
    public void setIsExpired(Integer isExpired) {
        this.isExpired = isExpired;
    }

    
    @Column(name="created_by", length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    
    @Column(name="updated_by", length=45)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_on", length=19)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="hrmUser")
    public Set<HrmUserRole> getHrmUserRoles() {
        return this.hrmUserRoles;
    }
    
    public void setHrmUserRoles(Set<HrmUserRole> hrmUserRoles) {
        this.hrmUserRoles = hrmUserRoles;
    }




}


