package com.inkubator.hrm.entity;
// Generated Mar 6, 2014 12:14:43 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PhysicalAbilityPositionId generated by hbm2java
 */
@Embeddable
public class PhysicalAbilityPositionId  implements java.io.Serializable {


     private long physicalAbilityId;
     private long positionId;

    public PhysicalAbilityPositionId() {
    }

    public PhysicalAbilityPositionId(long physicalAbilityId, long positionId) {
       this.physicalAbilityId = physicalAbilityId;
       this.positionId = positionId;
    }
   


    @Column(name="physical_ability_id", nullable=false)
    public long getPhysicalAbilityId() {
        return this.physicalAbilityId;
    }
    
    public void setPhysicalAbilityId(long physicalAbilityId) {
        this.physicalAbilityId = physicalAbilityId;
    }


    @Column(name="position_id", nullable=false)
    public long getPositionId() {
        return this.positionId;
    }
    
    public void setPositionId(long positionId) {
        this.positionId = positionId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PhysicalAbilityPositionId) ) return false;
		 PhysicalAbilityPositionId castOther = ( PhysicalAbilityPositionId ) other; 
         
		 return (this.getPhysicalAbilityId()==castOther.getPhysicalAbilityId())
 && (this.getPositionId()==castOther.getPositionId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getPhysicalAbilityId();
         result = 37 * result + (int) this.getPositionId();
         return result;
   }   


}


