package com.inkubator.hrm.entity;
// Generated Mar 6, 2014 12:14:43 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * PhysicalAbility generated by hbm2java
 */
@Entity
@Table(name="physical_ability"
    ,catalog="hrm"
    , uniqueConstraints = @UniqueConstraint(columnNames="physical_ability_name") 
)
public class PhysicalAbility  implements java.io.Serializable {


     private long id;
     private Integer version;
     private String physicalAbilityName;
     private String scalaNilai;
     private String createdBy;
     private Date createdOn;
     private String updatedBy;
     private Date updatedOn;
     private Set<PhysicalAbilityPosition> physicalAbilityPositions = new HashSet<PhysicalAbilityPosition>(0);

    public PhysicalAbility() {
    }

	
    public PhysicalAbility(long id) {
        this.id = id;
    }
    public PhysicalAbility(long id, String physicalAbilityName, String scalaNilai, String createdBy, Date createdOn, String updatedBy, Date updatedOn, Set<PhysicalAbilityPosition> physicalAbilityPositions) {
       this.id = id;
       this.physicalAbilityName = physicalAbilityName;
       this.scalaNilai = scalaNilai;
       this.createdBy = createdBy;
       this.createdOn = createdOn;
       this.updatedBy = updatedBy;
       this.updatedOn = updatedOn;
       this.physicalAbilityPositions = physicalAbilityPositions;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    
    @Column(name="physical_ability_name", unique=true, length=45)
    public String getPhysicalAbilityName() {
        return this.physicalAbilityName;
    }
    
    public void setPhysicalAbilityName(String physicalAbilityName) {
        this.physicalAbilityName = physicalAbilityName;
    }

    
    @Column(name="scala_nilai", length=25)
    public String getScalaNilai() {
        return this.scalaNilai;
    }
    
    public void setScalaNilai(String scalaNilai) {
        this.scalaNilai = scalaNilai;
    }

    
    @Column(name="created_by", length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="updated_by", length=45)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_on", length=19)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="physicalAbility")
    public Set<PhysicalAbilityPosition> getPhysicalAbilityPositions() {
        return this.physicalAbilityPositions;
    }
    
    public void setPhysicalAbilityPositions(Set<PhysicalAbilityPosition> physicalAbilityPositions) {
        this.physicalAbilityPositions = physicalAbilityPositions;
    }




}


