package com.inkubator.hrm.entity;
// Generated Mar 6, 2014 12:14:43 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * PosBiaya generated by hbm2java
 */
@Entity
@Table(name="pos_biaya"
    ,catalog="hrm"
    , uniqueConstraints = @UniqueConstraint(columnNames="pos_biaya_code") 
)
public class PosBiaya  implements java.io.Serializable {


     private long id;
     private Integer version;
     private String posBiayaCode;
     private String posBiayaName;
     private String createdBy;
     private Date createdOn;
     private String updatedBy;
     private Date updatedOn;
     private Set<Position> positions = new HashSet<Position>(0);

    public PosBiaya() {
    }

	
    public PosBiaya(long id) {
        this.id = id;
    }
    public PosBiaya(long id, String posBiayaCode, String posBiayaName, String createdBy, Date createdOn, String updatedBy, Date updatedOn, Set<Position> positions) {
       this.id = id;
       this.posBiayaCode = posBiayaCode;
       this.posBiayaName = posBiayaName;
       this.createdBy = createdBy;
       this.createdOn = createdOn;
       this.updatedBy = updatedBy;
       this.updatedOn = updatedOn;
       this.positions = positions;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    
    @Column(name="pos_biaya_code", unique=true, length=6)
    public String getPosBiayaCode() {
        return this.posBiayaCode;
    }
    
    public void setPosBiayaCode(String posBiayaCode) {
        this.posBiayaCode = posBiayaCode;
    }

    
    @Column(name="pos_biaya_name", length=100)
    public String getPosBiayaName() {
        return this.posBiayaName;
    }
    
    public void setPosBiayaName(String posBiayaName) {
        this.posBiayaName = posBiayaName;
    }

    
    @Column(name="created_by", length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="updated_by", length=45)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_on", length=19)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="posBiaya")
    public Set<Position> getPositions() {
        return this.positions;
    }
    
    public void setPositions(Set<Position> positions) {
        this.positions = positions;
    }




}


